url: https://convox.com

excerpt_separator: <!--more-->

kramdown:
  input: GFM

permalink: /blog/:title/

description: Convox is the easiest way to deploy your application to the cloud

collections:

defaults:
  - scope:
      path: cases
    values:
      layout: cases
  - scope:
      path: jobs
    values:
      layout: jobs
  - scope:
      path: legal
    values:
      layout: legal
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      path: pricing
    values:
      layout: pricing

exclude: [vendor]
